//! `--cargo DIR`: the output as a Cargo project, split into modules, with a
//! `main` that runs the decompiled one (docs/cli.md#cargo-projects).
//!
//! ```text
//! DIR/Cargo.toml
//! DIR/src/main.rs              calls `decompiled::main` with argc, argv, envp
//! DIR/src/decompiled/mod.rs    lint allows, `simd`, and a `pub use` of every module
//! DIR/src/decompiled/types.rs  recovered structs
//! DIR/src/decompiled/ffi.rs    the externs
//! DIR/src/decompiled/data.rs   the statics
//! DIR/src/decompiled/crt.rs    `_start`, `_init` and the rest of the C runtime's code
//! DIR/src/decompiled/<m>.rs    the functions, grouped by `group`
//! ```
//!
//! Every module starts with `use super::*;` and `mod.rs` re-exports them all, so
//! the code reads exactly as in one file: functions call each other, and name
//! statics and structs, without paths. Identifiers are unique across the output
//! already, so the globs never clash. Without a decompiled `main` the crate is a
//! library (`src/lib.rs`).
use crate::program::PreludeParts;
use std::collections::{BTreeMap, HashSet};
use std::fmt::Write as _;
use std::io;
use std::path::Path;

/// One emitted function (or its `todo!()` stub), with its header comment.
pub struct Piece {
    /// Demangled if possible.
    pub name: String,
    pub addr: u64,
    pub src: String,
}

/// The decompiled `main` the generated `fn main` calls.
pub struct Main {
    /// Its identifier, or its raw twin's in safe mode (which takes integers).
    pub ident: String,
    /// Integer arguments it takes (register and stack), then float arguments.
    pub args: usize,
    pub fargs: usize,
}

pub struct Project<'a> {
    /// What it was decompiled from, for the comments.
    pub source: &'a str,
    pub mode: &'a str,
    /// The Cargo package name.
    pub package: String,
    pub prelude: PreludeParts,
    /// The statics with `globals::PRELUDE`, or empty.
    pub statics: String,
    /// In output order.
    pub funcs: Vec<Piece>,
    pub main: Option<Main>,
    /// Compilation units from the debug info: `(low, high, name)` (`units`).
    pub units: Vec<(u64, u64, String)>,
    /// Shared libraries to link besides the ones Rust's std links (`needed`).
    pub libs: Vec<String>,
}

/// Functions per module when nothing better groups them.
const CHUNK: usize = 64;

/// Startup and teardown code the C compiler and linker add to every program.
const CRT: &[&str] = &[
    "_start", "_init", "_fini", "deregister_tm_clones", "register_tm_clones", "__do_global_dtors_aux",
    "frame_dummy", "__libc_csu_init", "__libc_csu_fini", "_dl_relocate_static_pie", "__do_global_ctors_aux",
    "__dso_handle", "__x86_indirect_thunk", "_start_c",
];

/// The first line of a generated Cargo.toml: `write` only replaces projects with it.
const MARKER: &str = "# Generated by chungusite";

/// Write the project to `dir`; the module names it split the functions into.
/// A `Cargo.toml` that chungusite didn't generate is never overwritten, and
/// `src/decompiled` is replaced as a whole.
pub fn write(dir: &Path, p: &Project) -> io::Result<Vec<String>> {
    let toml = dir.join("Cargo.toml");
    if let Ok(old) = std::fs::read_to_string(&toml) {
        if !old.starts_with(MARKER) {
            return Err(io::Error::other(format!("{} exists and wasn't generated by chungusite", toml.display())));
        }
    }
    let src = dir.join("src");
    let module_dir = src.join("decompiled");
    match std::fs::remove_dir_all(&module_dir) {
        Err(e) if e.kind() != io::ErrorKind::NotFound => return Err(e),
        _ => {}
    }
    std::fs::create_dir_all(&module_dir)?;

    let _ = std::fs::remove_file(src.join(if p.main.is_some() { "lib.rs" } else { "main.rs" }));
    std::fs::write(&toml, cargo_toml(p))?;
    if !dir.join(".gitignore").exists() {
        std::fs::write(dir.join(".gitignore"), "/target\n")?;
    }
    match &p.main {
        Some(m) => std::fs::write(src.join("main.rs"), main_rs(p, m))?,
        None => std::fs::write(
            src.join("lib.rs"),
            format!("//! Decompiled by chungusite from {} (--mode {}).\npub mod decompiled;\n", p.source, p.mode),
        )?,
    }

    let structs: HashSet<&str> =
        p.prelude.structs.lines().filter_map(|l| l.strip_prefix("pub struct ")).map(|l| l.split([' ', '<', '(', '{']).next().unwrap()).collect();
    let groups = group(&p.funcs, &p.units, &structs);

    let mut root = format!("//! Decompiled by chungusite from {} (--mode {}).\n", p.source, p.mode);
    root.push_str("#![allow(unknown_lints)]\n");
    root.push_str("#![allow(unused_mut, unused_variables, unused_assignments, unreachable_code, non_snake_case, non_upper_case_globals, non_camel_case_types, unused_parens, unused_unsafe, unused_imports, unused_comparisons, unused_labels, overflowing_literals, unconditional_recursion, improper_ctypes, suspicious_runtime_symbol_definitions, dead_code, static_mut_refs, clippy::all)]\n\n");
    let mut modules: Vec<&str> = Vec::new();
    if !p.prelude.structs.is_empty() {
        modules.push("types");
        let body = format!("//! Structs recovered from debug info and field accesses.\nuse super::*;\n{}", p.prelude.structs);
        std::fs::write(module_dir.join("types.rs"), body)?;
    }
    if !p.prelude.ffi.is_empty() {
        let _ = writeln!(root, "/// Functions the decompiled code calls but doesn't define.\npub mod ffi;");
        let body: String = p.prelude.ffi.lines().map(|l| format!("{}\n", l.strip_prefix("    ").unwrap_or(l))).collect();
        std::fs::write(module_dir.join("ffi.rs"), format!("//! Functions the decompiled code calls but doesn't define.\nuse super::*;\n\n{body}"))?;
    }
    if !p.statics.is_empty() {
        modules.push("data");
        let body = p.statics.trim_start().replacen("// Data the functions above point into", "//! Data the functions point into", 1);
        std::fs::write(module_dir.join("data.rs"), format!("{}\nuse super::*;\n\n{}", first_line(&body), rest(&body)))?;
    }
    for (name, items) in &groups {
        let mut s = String::new();
        let lo = items.iter().map(|&i| p.funcs[i].addr).min().unwrap_or(0);
        let _ = writeln!(s, "//! {} functions, from {lo:#x}.\nuse super::*;", items.len());
        for &i in items {
            s.push_str(&p.funcs[i].src);
        }
        std::fs::write(module_dir.join(format!("{name}.rs")), s)?;
        modules.push(name);
    }
    for m in &modules {
        let _ = writeln!(root, "pub mod {m};");
    }
    root.push('\n');
    for m in &modules {
        let _ = writeln!(root, "pub use self::{m}::*;");
    }
    if !p.libs.is_empty() {
        root.push_str("\n// The shared libraries the binary links, besides libc.\n");
        for l in &p.libs {
            let _ = writeln!(root, "#[link(name = {l:?}, modifiers = \"+verbatim\")]");
        }
        root.push_str("extern \"C\" {}\n");
    }
    if p.prelude.simd {
        root.push_str(crate::simd::PRELUDE);
    }
    std::fs::write(module_dir.join("mod.rs"), root)?;
    Ok(groups.into_iter().map(|(n, _)| n).collect())
}

fn first_line(s: &str) -> &str {
    s.lines().next().unwrap_or("")
}

fn rest(s: &str) -> &str {
    s.split_once('\n').map_or("", |(_, r)| r)
}

/// Which module each function goes in, as `(module, indices into funcs)` in
/// order of each module's first function: the C runtime's code in `crt`; a
/// Rust or C++ function by its namespace (`core::fmt::write` in `core_fmt`);
/// one with debug info by its source file (`list.c` in `list_c`); the rest in
/// address order, `CHUNK` per module, since linkers keep each object file's
/// functions together.
pub fn group(funcs: &[Piece], units: &[(u64, u64, String)], structs: &HashSet<&str>) -> Vec<(String, Vec<usize>)> {
    let mut by_name: BTreeMap<String, (usize, Vec<usize>)> = BTreeMap::new();
    let mut rest = Vec::new();
    for (i, f) in funcs.iter().enumerate() {
        let module = if CRT.contains(&f.name.as_str()) {
            Some("crt".to_string())
        } else if let Some(ns) = namespace(&f.name) {
            Some(ns)
        } else {
            units.iter().find(|(lo, hi, _)| (*lo..*hi).contains(&f.addr)).map(|(_, _, n)| file_module(n))
        };
        match module {
            Some(m) => by_name.entry(normalize(&m)).or_insert((i, Vec::new())).1.push(i),
            None => rest.push(i),
        }
    }
    let chunks = rest.len().div_ceil(CHUNK);
    for (k, c) in rest.chunks(CHUNK).enumerate() {
        let m = if chunks == 1 { "code".to_string() } else { format!("code_{:0w$}", k + 1, w = chunks.to_string().len()) };
        by_name.entry(m).or_insert((c[0], Vec::new())).1.extend(c);
    }
    let mut out: Vec<(String, Vec<usize>)> = Vec::new();
    let mut taken = HashSet::new();
    let mut v: Vec<_> = by_name.into_iter().collect();
    v.sort_by_key(|(_, (first, _))| *first);
    for (name, (_, items)) in v {
        out.push((module_ident(&name, structs, &mut taken), items));
    }
    out
}

/// `core::fmt::write` -> `core_fmt`, `<alloc::vec::Vec<T> as Drop>::drop` ->
/// `alloc_vec`: the first two path segments before the function's own name.
fn namespace(name: &str) -> Option<String> {
    let mut path = name;
    // `<T as Trait>::f` and `<T>::f` are T's
    if path.starts_with('<') {
        let inner = path.trim_start_matches(['<', '&']);
        let end = inner.find([' ', '>']).unwrap_or(inner.len());
        path = &inner[..end];
        if !path.contains("::") {
            return None;
        }
        return Some(path.split("::").take(2).collect::<Vec<_>>().join("_"));
    }
    let mut segs = Vec::new();
    let (mut depth, mut start) = (0, 0);
    let b = path.as_bytes();
    let mut k = 0;
    while k < b.len() {
        match b[k] {
            b'<' | b'(' => depth += 1,
            b'>' | b')' => depth -= 1,
            b':' if depth == 0 && b.get(k + 1) == Some(&b':') => {
                segs.push(&path[start..k]);
                start = k + 2;
                k += 1;
            }
            _ => {}
        }
        k += 1;
    }
    if segs.is_empty() {
        return None;
    }
    Some(segs.iter().take(2).map(|s| s.split('<').next().unwrap()).collect::<Vec<_>>().join("_"))
}

/// `src/list.c` -> `list_c`.
fn file_module(unit: &str) -> String {
    // rustc names units `src/main.rs/@/crate.hash-cgu.0`
    let unit = unit.split("/@/").next().unwrap_or(unit);
    unit.rsplit(['/', '\\']).next().unwrap_or(unit).to_string()
}

/// `name` as an identifier: lower case, one `_` between words.
fn normalize(name: &str) -> String {
    let mut s = crate::names::sanitize(&name.to_ascii_lowercase());
    while s.contains("__") {
        s = s.replace("__", "_");
    }
    s
}

/// A module name for `name`: lower case, and not a name the code needs for
/// something else (the other modules, a struct, a crate in paths).
fn module_ident(name: &str, structs: &HashSet<&str>, taken: &mut HashSet<String>) -> String {
    const RESERVED: &[&str] = &["types", "ffi", "data", "simd", "std", "core", "alloc", "decompiled", "crate", "self", "super"];
    let mut s = normalize(name);
    if RESERVED.contains(&s.as_str()) {
        s.push('_');
    }
    while structs.contains(s.as_str()) || !taken.insert(s.clone()) {
        s.push('_');
    }
    s
}

fn cargo_toml(p: &Project) -> String {
    format!(
        "{MARKER} from {} (--mode {}).\n# Running chungusite --cargo here again replaces src/.\n\
         [package]\nname = {:?}\nversion = \"0.1.0\"\nedition = \"2021\"\npublish = false\n\n\
         # Not a member of any workspace this directory is in.\n[workspace]\n\n[dependencies]\n",
        p.source, p.mode, p.package
    )
}

/// The Cargo package name for a binary at `path`.
pub fn package_name(path: &str) -> String {
    let stem = Path::new(path).file_stem().and_then(|s| s.to_str()).unwrap_or("");
    let mut s: String =
        stem.chars().map(|c| if c.is_ascii_alphanumeric() || c == '-' || c == '_' { c.to_ascii_lowercase() } else { '_' }).collect();
    s = s.trim_matches(['_', '-']).to_string();
    let reserved = ["test", "std", "core", "alloc", "proc_macro", "proc-macro", "build", "deps", "examples", "incremental"];
    if s.is_empty() || s.starts_with(|c: char| c.is_ascii_digit()) || reserved.contains(&s.as_str()) {
        s = format!("decompiled-{s}").trim_end_matches('-').to_string();
    }
    s
}

fn main_rs(p: &Project, m: &Main) -> String {
    let mut args: Vec<&str> = ["args.len() as _", "argv.as_ptr() as _", "envp.as_ptr() as _"].into_iter().take(m.args).collect();
    args.extend((args.len()..m.args).map(|_| "0 as _"));
    args.extend((0..m.fargs).map(|_| "0.0"));
    format!(
        r#"//! Decompiled by chungusite from {source} (--mode {mode}). `cargo run -- ARGS`
//! runs the decompiled `main` with ARGS.
mod decompiled;

use std::ffi::{{c_char, CString}};
use std::os::unix::ffi::OsStrExt;

/// What the decompiled `main` returns, as an exit status.
trait Status {{
    fn code(self) -> i32;
}}
impl Status for () {{
    fn code(self) -> i32 {{
        0
    }}
}}
impl Status for (u64, u64) {{
    fn code(self) -> i32 {{
        self.0 as i32
    }}
}}
macro_rules! status {{
    ($($t:ty),*) => {{ $(impl Status for $t {{ fn code(self) -> i32 {{ self as i32 }} }})* }};
}}
status!(u8, u16, u32, u64, i8, i16, i32, i64, bool, f64);

fn main() {{
    // argv and envp as C gets them: NUL-terminated strings, then a null pointer.
    let args: Vec<CString> = std::env::args_os().map(|a| CString::new(a.as_bytes()).unwrap()).collect();
    let env: Vec<CString> = std::env::vars_os()
        .map(|(k, v)| CString::new([k.as_bytes(), b"=", v.as_bytes()].concat()).unwrap())
        .collect();
    let argv: Vec<*const c_char> = args.iter().map(|a| a.as_ptr()).chain([std::ptr::null()]).collect();
    let envp: Vec<*const c_char> = env.iter().map(|a| a.as_ptr()).chain([std::ptr::null()]).collect();
    let _ = (&argv, &envp);
    #[allow(unused_unsafe)]
    let status = unsafe {{ decompiled::{ident}({args}) }};
    std::process::exit(Status::code(status));
}}
"#,
        source = p.source,
        mode = p.mode,
        ident = m.ident,
        args = args.join(", "),
    )
}

/// The compilation units in `data`'s debug info, as `(low, high, name)` address
/// ranges; empty without DWARF.
pub fn units(data: &[u8]) -> Vec<(u64, u64, String)> {
    use gimli::{EndianSlice, LittleEndian};
    use object::{Object, ObjectSection};
    let Ok(file) = object::File::parse(data) else { return Vec::new() };
    if file.section_by_name(".debug_info").is_none() {
        return Vec::new();
    }
    let load = |id: gimli::SectionId| -> Result<std::borrow::Cow<[u8]>, gimli::Error> {
        Ok(file.section_by_name(id.name()).and_then(|s| s.uncompressed_data().ok()).unwrap_or_default())
    };
    let Ok(sections) = gimli::DwarfSections::load(load) else { return Vec::new() };
    let dwarf = sections.borrow(|s| EndianSlice::new(s, LittleEndian));
    let mut out = Vec::new();
    let mut headers = dwarf.units();
    while let Ok(Some(h)) = headers.next() {
        let Ok(unit) = dwarf.unit(h) else { continue };
        let Some(name) = unit.name.and_then(|n| n.to_string().ok().map(str::to_string)) else { continue };
        let Ok(mut ranges) = dwarf.unit_ranges(&unit) else { continue };
        while let Ok(Some(r)) = ranges.next() {
            out.push((r.begin, r.end, name.clone()));
        }
    }
    out
}

/// The shared libraries an ELF file needs (its `DT_NEEDED` entries), less the
/// ones every Rust program on Linux links already.
pub fn needed(data: &[u8]) -> Vec<String> {
    use object::{Object, ObjectSection};
    const STD: &[&str] = &["libc.so", "libm.so", "libpthread.so", "libdl.so", "librt.so", "libutil.so", "libgcc_s.so", "ld-linux"];
    let Ok(file) = object::File::parse(data) else { return Vec::new() };
    if file.format() != object::BinaryFormat::Elf {
        return Vec::new();
    }
    let (Some(dynamic), Some(strs)) = (file.section_by_name(".dynamic"), file.section_by_name(".dynstr")) else {
        return Vec::new();
    };
    let (Ok(dynamic), Ok(strs)) = (dynamic.data(), strs.data()) else { return Vec::new() };
    let mut out = Vec::new();
    for e in dynamic.chunks_exact(16) {
        let tag = u64::from_le_bytes(e[..8].try_into().unwrap());
        let val = u64::from_le_bytes(e[8..].try_into().unwrap()) as usize;
        match tag {
            0 => break,
            1 => {
                let Some(name) = strs.get(val..).and_then(|s| s.split(|&b| b == 0).next()) else { continue };
                let name = String::from_utf8_lossy(name).into_owned();
                if !STD.iter().any(|s| name.starts_with(s)) {
                    out.push(name);
                }
            }
            _ => {}
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn namespaces() {
        assert_eq!(namespace("core::fmt::write").as_deref(), Some("core_fmt"));
        assert_eq!(namespace("std::rt::lang_start").as_deref(), Some("std_rt"));
        assert_eq!(namespace("<alloc::vec::Vec<T> as core::ops::Drop>::drop").as_deref(), Some("alloc_vec"));
        assert_eq!(namespace("<<alloc::boxed::Box<T> as From<S>>::from::E as Error>::cause").as_deref(), Some("alloc_boxed"));
        assert_eq!(namespace("<&core::num::Wrapping<u8> as Debug>::fmt").as_deref(), Some("core_num"));
        assert_eq!(namespace("foo::bar").as_deref(), Some("foo"));
        assert_eq!(namespace("main"), None);
        assert_eq!(namespace("<i32 as Debug>::fmt"), None);
    }

    #[test]
    fn modules() {
        let mut taken = HashSet::new();
        let none = HashSet::new();
        assert_eq!(module_ident("list.c", &none, &mut taken), "list_c");
        assert_eq!(module_ident("list.c", &none, &mut taken), "list_c_");
        assert_eq!(module_ident("core", &none, &mut taken), "core_");
        assert_eq!(module_ident("crt", &none, &mut taken), "crt");
        let structs: HashSet<&str> = ["node"].into();
        assert_eq!(module_ident("node", &structs, &mut taken), "node_");
        assert_eq!(package_name("/tmp/my prog"), "my_prog");
        assert_eq!(package_name("./7z"), "decompiled-7z");
    }
}
